<h1 class="title"><?php print $title;?></h1>
<div class="event-image"><?php print $image;?></div>
<div class="event-organization">Организация: <?php print $organization;?></div>
<div class="event-place">Место: <?php print $place;?></div>
<div class="event-description"><?php print $description;?></div>
<div class="event-category">Категория: <?php print $category;?></div>
<div class="event-tags">Тэги: <?php print $tags;?></div>
<div class="event-persons"><?php print $persons;?></div>
<div class="event-price"><?php print $price;?></div>
<div class="event-seances"><?php print $seances;?></div>
<div class="event-address">Адрес: <?php print $address;?></div>
<div class="event-map"><?php print $map;?></div>
<div class="event-gallery"><?php print $gallery;?></div>